// Confirmed live 2026-07-23 against real suggestions generated by the pipeline. One real quirk:
// `newText` (never `oldText`) consistently arrives with literal wrapping quote characters baked
// into the string content itself (e.g. the actual value is `"JavaScript, Node.js"` including the
// quote marks) — a backend generation artifact, stripped for display in SuggestionCard rather
// than rendered as-is, since showing doubled-up quote marks in an already-labeled "Suggested" box
// reads as a display bug, not real content.
export interface AiSuggestion {
  id: string;
  sectionType: "summary" | "experience" | "projects" | "skills";
  itemIndex: number | null; // which entry within the section
  bulletIndex: number | null; // which bullet within the entry (null = whole item)
  oldText: string;
  newText: string;
  reason: string;
  impact: "high" | "medium" | "low";
  keywordsAdded: string[];
  // needs_info: the fabrication guard couldn't verify newText against the resume, so it's saved
  // instead of dropped. On a needs_info row, BOTH newText and exampleValue are illustrative-only
  // (the AI invented them) — never render them as an applyable diff the way a pending row's
  // newText is rendered.
  status: "pending" | "accepted" | "rejected" | "stale" | "needs_info";
  missingFact: string | null; // only populated on needs_info — what fact the AI couldn't verify
  exampleValue: string | null; // only populated on needs_info — an illustrative, fabricated example
  // true when the violation is an unsupported skill/technology claim (e.g. the AI tried to add
  // "Unity" with zero resume evidence) — provide-detail can NEVER resolve this, since it checks
  // the resubmitted text against the resume's frozen original text, which can never contain a
  // skill added after upload. missingFact is already a complete, standalone sentence explaining
  // this and pointing at editing the resume directly; exampleValue is always null on these rows.
  needsDirectEdit: boolean;
}

export interface ApplySuggestionsResult {
  version: number;
  applied: number;
  skipped: string[];
}
