// Confirmed live 2026-07-23 against real suggestions generated by the pipeline. One real quirk:
// `newText` (never `oldText`) consistently arrives with literal wrapping quote characters baked
// into the string content itself (e.g. the actual value is `"JavaScript, Node.js"` including the
// quote marks) — a backend generation artifact, stripped for display in SuggestionCard rather
// than rendered as-is, since showing doubled-up quote marks in an already-labeled "Suggested" box
// reads as a display bug, not real content.
export interface AiSuggestion {
  id: string;
  sectionType: "summary" | "experience" | "projects" | "skills";
  itemIndex: number | null; // which entry within the section
  bulletIndex: number | null; // which bullet within the entry (null = whole item)
  oldText: string;
  newText: string;
  reason: string;
  impact: "high" | "medium" | "low";
  keywordsAdded: string[];
  status: "pending" | "accepted" | "rejected" | "stale";
}

export interface ApplySuggestionsResult {
  version: number;
  applied: number;
  skipped: string[];
}
